package com.liyun.car.param.entity;

import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.liyun.car.common.enums.ParamStatusEnum;
import com.liyun.car.common.serializer.EnumSerializer;
import com.liyun.car.param.enums.DepartmentLevelEnum;



/**
 * SyDepartment generated by MyEclipse - Hibernate Tools
 */

public class SyDepartment  implements java.io.Serializable {


    // Fields    

	private static final long serialVersionUID = 1L;
	private Integer departmentId;
    private String departmentName;
    private DepartmentLevelEnum departmentLevel;
    private SyDepartment parDepartment;
    private String remark;
    private ParamStatusEnum status;
    private Date crtTime;
    private String role;
    
	public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@JsonSerialize(using = EnumSerializer.class)
	public DepartmentLevelEnum getDepartmentLevel() {
		return departmentLevel;
	}

	public void setDepartmentLevel(DepartmentLevelEnum departmentLevel) {
		this.departmentLevel = departmentLevel;
	}

	@JsonSerialize(using = EnumSerializer.class)
	public ParamStatusEnum getStatus() {
		return status;
	}

	public void setStatus(ParamStatusEnum status) {
		this.status = status;
	}

	public SyDepartment getParDepartment() {
		return parDepartment;
	}

	public void setParDepartment(SyDepartment parDepartment) {
		this.parDepartment = parDepartment;
	}

	public Date getCrtTime() {
		return crtTime;
	}

	public void setCrtTime(Date crtTime) {
		this.crtTime = crtTime;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}


    
}