package com.liyun.car.param.entity;


import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.liyun.car.common.entity.Dict;
import com.liyun.car.common.enums.ParamStatusEnum;
import com.liyun.car.common.serializer.EnumSerializer;


/**
 * SyArgControl generated by MyEclipse - Hibernate Tools
 */

public class SyDict  extends Dict implements java.io.Serializable {


    // Fields    

	private Integer id;
	private ParamStatusEnum status;
	private String value;
	private Date conArgStartdate;
	private Date conArgStopdate;
	
	private SyDict dict;

	// Constructors

	/** default constructor */
	public SyDict() {
	}

	public SyDict(Integer id, String code) {
		super();
		this.id = id;
		super.code = code;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonSerialize(using = EnumSerializer.class)
	public ParamStatusEnum getStatus() {
		return status;
	}

	public void setStatus(ParamStatusEnum status) {
		this.status = status;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Date getConArgStartdate() {
		return conArgStartdate;
	}

	public void setConArgStartdate(Date conArgStartdate) {
		this.conArgStartdate = conArgStartdate;
	}

	public Date getConArgStopdate() {
		return conArgStopdate;
	}

	public void setConArgStopdate(Date conArgStopdate) {
		this.conArgStopdate = conArgStopdate;
	}

	public SyDict getDict() {
		return dict;
	}

	public void setDict(SyDict dict) {
		this.dict = dict;
	}


}